wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701949715.281068
    t:
      1:
      - 55
      2:
      - 1
      - 3
      - 9
      - 41
      - 55
      - 103
      3:
      - 2
      - 13
      - 23
      4: 3.8.18
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
    framework: lightning
