# Communication parameters
common: &common
  noise_type: '' # AWGN, Rayleigh, Rician
  k_ratio: 0 # For Rayleigh channel
  snr_db: 10
tradicom:
  n_ldpc: 6144
  k_ldpc: 2048
  num_bits_per_symbol: 6
  demapping_method: 'app'
  ldpc_cn_type: 'boxplus'
  <<: *common
jscc:
  zdim: 4096
  channels: [64, 128, 256, 512, 512, 512]
  n_res_block: 2
  dim_cond: 0
  type_upsample: 'upsample'
  # QAM
  n_qam: 64
  length_edge: 4
  detector: 'LS' # 'LS', 'MMSE'
  # Power
  power: null # number or null 
  use_power_norm: False
  <<: *common


  
